  version: 2.1
  jobs:
    build:
      working_directory: ~/myapp
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - checkout # check out the code in the project directory
        - run:
            name: update-npm
            command: 'sudo npm install -g npm@5.6.0'
        - run:
            name: ls test
            command: 'ls -ltr'
        - run:
            name: pwd test
            command: 'pwd'
        - run:
            name: npm install
            command: npm install
            working_directory: ~/myapp/myapp
        - run:
            name: build
            command: npm run build
            working_directory: ~/myapp/myapp
        - add_ssh_keys:
            fingerprints:
              - "7b:d7:fc:a8:5d:30:94:7f:6d:d9:6b:94:48:f9:83:ae"

